* Characters
- Madeleina (Leina) Grey - The main character of our story
  - Leina is a tormented kid. She is way too mature and intellgent for her age.
  - She does not like adults. She hates the idea of politics. She wants to be free.
  - young girl
  - self-reliant
  - wants freedom and peace
  - tormented
  - way too mature and intellgent for her age
  - healthy disrespect for adults and politics
  - wants freedom, solitude, a simple life
- Alistair Grey - Leina's father
- Haesius Moore - Nume's brother, Leina's uncle
- Nume Moore Grey - Leina's mother
- Ardovus Retik - the assassin sent to find Leina
- The "Reds" Red Shepherds (Faction) - A militaristic political group led by the Collector.
- The Protector - The Leader of the Reds
- The Collector(s) - A group of elite Reds and a fabled band which operates in secrecy to do the Protector's will. Everyone pays tribute to the Collector(s), through groups such as the Red Shepherds. It’s not known who is in charge (it’s somewhat faceless, like anonymous).
- Sammy Smithens - the town librarian
- Johan Lemeus - Leina's next door neighbor who used to be in the guard, he is having an affair with Lindy Abnigale
- Lindy Abnigale - She works at the market
