* Unorganized Notes

This document is mostly deprecated ...

** Classes:
- Grace
- Seekers


** Places?

- Blackmoor?
- Westhaven?

** Character Ideas
- General Hadyn Throeau - a historic figure somehow related to Leina
- Jina (samwise-like; patient, quiet, doesn't talk, whispers to Leina), Saria, Rena, Zeeza, Mena, Sanja
- The School of Five? (ideas)
   1. Sielaph: Strength, brave (Man)
   2. Cassiel: Charisma, manipulating (Woman)
   3. Yisidy: Wisdom & Intelligence (Woman)
   4. Ditre: Dexterious (Woman)
   5. Osula: Endurance/Constitution, the outlaster (Man)

Leina demands the Assassin gives her a tattoo to codify their
alliance. Every additional person who joins the school is required to
tattoo a point and connect the dots from an existing point... Decentralized graph :) 

- Greyskins? - humans forced into slavery living underground, injected with serum, passed down through generations.
-- enhancing / experimenting?

**  Questions
- Is there religion?

The story begins in chaos with an alchemist being torn from his family
to join the Red Shepard's military effort to attack the very same
town. The alchemist is with his wife, his daughter of five, Leina,
and his youngest son, Reygon, of three. Red Shepard's threatened death
of their families. Military successfully siezes the town. The father
had refused to help, tried to flee / help family escape.  Father and
mother are burned to death as example. Brother was crying, is taken,
Leina had a better hiding spot.

Q: What is the Red Shepard's cause? Who do they serve?

Leina taken in by foster parents.

Son/brother becomes her nemisis.

Leina has a childhood friend

Who

Geryon [nick-name for Leina?] is a loner, she lives by a set of principles
- Avoid people contact unless necessary
- Change appearances weekly
- Do not stay in one place for too long
- wears a necklace
- Plans meticulously

Leina is told a story about a prophecy?


** 1. Greyskins

In the land of , there live three types of people, nobility,
commonfolk, and the greyskin.


Greyskins





Leina lives in her Uncle's house

Something important happened long ago which has been forgotten.
A deal was made? A people were exterminated? A thing was created? A book was written? Something was sealed?
Why? How?

* The Oracle

The Oracle is death. Where all souls go to die.
She takes your final breath, ne'er more to cry.

The Oracle can be controlled by certain people who fight amongst themselves to become Queen or King.

There are people beyond control of the Oracle of the "X" Class.

Power can only be extracted from the living creature

The presumed death of the last X Class. In truth, like moses, a kid was left without parents. That kid was Leina's great grandmother.

How/why does the Oracle exist? The story is told in a book.

What is the project Leina is given?
By a religious sentry.
She has to destroy the Oracle.

People have abilities, skills in this world (classes). Most don't know how to use their abilities. The King's rewards certain people with powers through the Oracle. People are required to tithe to the Oracle. 

Her mother is discovered to have a power/class which hasn't been detected since the

What is the Oracle?
The oracle is a relic that can unlock one's abilities.

The prophecy is that  Oracle needs Leina to unlock X by activating herself.

Leina is needed, she is the key.
She has information?


* Ideas

Generally follows the mono-myth (Lord of the Rings-esque, no super powers though fantastical setting). Leina lives with her uncle who does little save from claim responsibility as her guardian. She is self-reliant and seeks mentorship from various places. She has no extraordinary capabilities other than an unhealthy "tiger-mother-esque" upbringing and overdeveloped sense of strategy / learned-ness and persuasion.

* Synopsis

It's Lord of the Rings / Harry Potter (Mono Myth) meets "Moneyball".

The general tone / setting of the epic is similar to Game of Thrones in that there are warring cities trying to gain an upper hand. There's one band which operates in secrecy which referred to as the "Collectors". Everyone pays tribute to the Collectors. It's not known who is in charge (it's somewhat faceless, like anonymous). The "Academy" which Leina happens to form throughout the story comes to unintentionally undermine the Collector's authority and sinister plans.

Plot: Story starts with an assassin, Ardovus Retik who is hired to locate a book which has information to undermine the Collectors. Leina's parents are murdered, father, mother, and then her uncle. She confronts Ardovus with leverage that she knows where the book is. Ardovus assumes strange "gandalf / obiwan" elder figure when they realize they can use each other for great gains; a la "Leon the Professional".

Ardovus looks after Leina, using and nurturing her skills for personal gain. As the story progresses, Leina plays "moneyball" and comes across a handful of young prodigies whom she saves and inducts into a society of her own called the Academy.

Interesting avenues to explore / riff on:
- an academy setting, the politics of running a (harry-potter-like) academy.
- the logistics of the "one" book, what book is it?
- the conflict of the Collectors and the backstory


A coming of age story of a girl with no particular physical or
atheletic gifts who is able to use her ravenous knowledge, unstoppable
will-power, and keen sensitivity of the human condition to save and
unite talented youths, rejected by the world, to her side. What starts
as a band of friends grows into a political power capable of resisting
tyrrany of an unjust world.




