* Books: The Trilogy of the Soul Seeker's Manual
** Book One: The Soul Seeker's Manual
- About the Soul Seeker's Manual & the Red Shepherd
- The accidental intertwining of fates between Leina and Ardovus (whose lives are literally mortally entangled)
- The tension and conflict between Leina and Ardovus (whose motivations are also opposed)
  - Leina to survive, avoid being captured by the Reds, and escape to the safehaven city of "Gendalyn", deemed capable of resisting the Red's tyranny
  - Ardovous wishes to remain on the good side of the Reds and protect his own life
- Nume's chest of secrets 
** Book Two: The Academy
- Leina establishes the Academy
- The Academy is discovered 
** Book Three
- The Protector has sacrificed or enslaved thousands in the service of gaining power and producing the Collectors 
- Leina goes with a team to meet the Protector, under the pretense of submitting, but will really try to join their fates, similar to how she did Ardovous did
  - She is overwhelmed by the Protector and unable to maintain control
- The Protector all but "kills" Leina, after her unsuccessful attempt, and commits her name to the Oracle -- thus unintentionally connecting the Protector to Ardovous
- Ardovous kills himself and immediately the Oracle becomes overwhelmed and begins to cause the Protector's city to crumble

* Stories / histories
** Story of the obsidial soul rock
** Story of Nume?
** Story of the Assassin?
** History of the soul seeker's manual
** History of the Protector & the Red Shepherds

* Plot points 
** Leina can choose how long assassin may be separated (e.g. 1 week, 1 hour)
** Leina can enhance herself via soul seeking
** Soul seeking takes its toll on the caster
** When soul seeking multiple people, hard to control, may cause personal injury
** Unintentionally, Leina needs the assassin to stay alive as they are uniquely linked (mistake)
** The assassin knows of Alistair, Leina's father, who is renowned
*** It's completely unclear the circumstances of his death. (similar to Boromir or Snape).
*** It's Alistair notes and annotations in the manual, but Leina won't learn this until much later

* Plot
** Stability: Leina grows up in a town
*** Leina learns and advances
*** One day Leina is playing by Oracle Rock and comes home to tell Nume she could tell someone had died, Nume has an episode 
*** Nume puts something in her secret chest (containing hints about her background and Leina's father)
*** Reds send assassin after owner of annotated soul seeker's manual
** Call to adventure: Mother encourages her to learn, soul-seek, etc?
** Refusal: Leaves home
** Supernatural aid: the Soul Seeker's Manual
*** Leina's mother is murdered
*** Leina encounters the assassin
*** Leina binds herself to the assassin to survive
** Crossing the 1st threshold: Leina reluctantly leaves with the assassin
** Belly of the whale: ???
*** Leina pushed to her limit, plan backfires
**** Unintentionally, Leina needs the assassin to stay alive as they are uniquely linked (inexperience, mistak$
*** Road of trials: ...
*** Meeting with the Goddess: Opportunity to run and hide, leaves assassin
**** Some promise of having fun, escaping responsibility
*** Attonement with Father & Mother 
**** Learns why Nume was such a tough personality, how her parents met, who her father really was
