* Books: Leina Grey

The story of Leina Grey is a monomyth / hero's journey, thematically most similar in world and intensity to the Lord of the Rings, but with a younger audience, accessible and fast-paced writing style, and emotional feel-good characteristics of harry potter. The world is pre-industrialization, earth-like, not magical, though some elements of the world are naturally fantastical in their own rights, similar to how science is real and almost magical in our world. In this world, there is a lost art called "soul seeking" which is the ability (similar to the "force" from Star Wars) for one to use one's life energy to catalyze interactions between cells. While this ability occurs naturally in the universe, certain materials and areas seem more conducive to performing "soul seeking". One such material is called the Oracle Stone, a type of black obsidian that behaves like a magnet for amplifying or focusing energies. One such rock formation, simply called, "The Oracle", extends deep into the earth and its gravity pulls energy towards it. A political faction called the Red Shepherds (or the "Reds"), under the merciless leadership of one named the "Protector", seeks to command the power of soul seeking to overcome their human limitations, to achieve mental and physical superiority, and to challenge death itself. They do so by establishing a centre near the Oracle and launching a campaign to find copies of texts about the lost art of soul seeking, called the "Soul Seeker's Manuals". A woman named Nume, has a particularly rare, annotated edition of this manual which is fabled to have notes that exist nowhere else and the Reds send assassins to discover its whereabouts. Nume becomes a casualty of one such assassin, Artivous, who then turns his search for her daughter, the 14 year old protagonist of our story: Leina Grey. When confronted, Leina is able to detect the assassin has a fatal heart condition, which she uses as leverage to even the playing field. In a moment of desperation, using her intimate connection with her family's special soul seeking manual, as well as her innate soul seeking affinities, she is able to bind her fate to the assassin's heart condition and thus triggers a sensitive standoff, where she must figure out how to stay one step ahead to survive. In the pursuit of survival, Leina must simultaneously yield to the assassin's agenda and leverage her soul seeking abilities and strategic prowess to amass enough power to gain the upper hand.

- thousands have died resisting the Protector and the Red Shepherds. Their souls have been returned to The Oracle, only furthering the Protector's drive for power.
- as the Reds knowledge increases, so do their capabilities, and they become closer to identifying the signature of the rebellious soul seekers, led by Leina -- simply called the "Defenders". On the precipice of being discovered, Leina must go on the offensive.
- Leina goes with a team to face the Protector. Her hope is to join his fate with hers, similar to what she did with Ardovous, and then to take her own life, thus taking the Protector with her.
- But Leina is overwhelmed by the Protector and unable to maintain control and the Protector commits her life force to the Oracle.
- Except the joining of fates had been successful, and what really happened unexpectedly is the Protector was joined not only to Leina but also to Ardovous, the assassin.
- Realizing this, Ardovous makes the impossible decision to kill himself and immediately the Oracle becomes overwhelmed, the Oracle because unstable, and the Protector's city begins to crumble

** Book One: The Book of Souls
- We learn of the Soul Seeker's Manual & the Red Shepherd
- The accidental intertwining of fates between Leina and Ardovus (whose lives are literally mortally entangled)
- The tension and conflict between Leina and Ardovus (whose motivations are also opposed)
  - Leina to survive, avoid being captured by the Reds, and escape to the safehaven city of "Gendalyn", deemed capable of resisting the Red's tyranny
  - Ardovous wishes to remain on the good side of the Reds and protect his own life
- Leina searches

** Book Two: The 
- Leina establishes the Academy
- The Academy is discovered 

** Book Three: 
- The Protector has sacrificed or enslaved thousands in the service of gaining power and producing the Collectors 
- Leina goes with a team to meet the Protector, under the pretense of submitting, but will really try to join their fates, similar to how she did Ardovous did
  - She is overwhelmed by the Protector and unable to maintain control
- The Protector all but "kills" Leina, after her unsuccessful attempt, and commits her name to the Oracle -- thus unintentionally connecting the Protector to Ardovous
- Ardovous kills himself and immediately the Oracle becomes overwhelmed and begins to cause the Protector's city to crumble

* Stories / histories
- Story of the obsidial soul rock
- Story of Nume?
- Story of the Assassin?
- History of the soul seeker's manual
- History of the Protector & the Red Shepherds

* Possible Plot Points 
- Leina can choose how long assassin may be separated (e.g. 1 week, 1 hour)
- Leina can enhance herself via soul seeking
- Soul seeking takes its toll on the caster
- When soul seeking multiple people, hard to control, may cause personal injury
- Unintentionally, Leina needs the assassin to stay alive as they are uniquely linked (mistake)
- The assassin knows of Alistair, Leina's father, who is renowned
- Nume's chest of secrets; when Nume dies, she is holding a key... the key does not go to the chest in her house, it goes to a box at Alistair's grave which contains a key to Nume's chest. What's in the chest?


- What is the Soul Seeker's Manual?
- Who are the Red Shepherds?
- Who leads the Red Shepherds?
- Who is Leina Grey?

* Ideas

* Plot
** Stability: Leina grows up in a town
*** Leina learns and advances
*** One day Leina is playing by Oracle Rock and comes home to tell Nume she could tell someone had died, Nume has an episode 
*** Nume puts something in her secret chest (containing hints about her background and Leina's father)
*** Reds send assassin after owner of annotated soul seeker's manual
** Call to adventure: Mother encourages her to learn, soul-seek, etc?
** Refusal: Leaves home
** Supernatural aid: the Soul Seeker's Manual
*** Leina's mother is murdered
*** Leina encounters the assassin
*** Leina binds herself to the assassin to survive
** Crossing the 1st threshold: Leina reluctantly leaves with the assassin
** Belly of the whale: ???
*** Leina pushed to her limit, plan backfires
**** Unintentionally, Leina needs the assassin to stay alive as they are uniquely linked (inexperience, mistak$
*** Road of trials: ...
*** Meeting with the Goddess: Opportunity to run and hide, leaves assassin
**** Some promise of having fun, escaping responsibility
*** Attonement with Father & Mother 
**** Learns why Nume was such a tough personality, how her parents met, who her father really was





