
* Prologue
The Academy is the story of Leina Grey, a young girl who assembles a
guild of prodigies to shield herself from an oppresive society. In her
persuit of evading conflic, she incites the biggest power-struggle
Westhaven has ever seen.

* The Academy

** Chapter I
"Show me to fight", Madeleina demanded of Johan Lemeus.

"To fight?", Johan chuckled playfully, his tone reminiscent of one
addressing a young child who had just said something cute, "Now who
could you want to be fighting?"

"Those who would want to fight me, Lemeus", Madeleina retorted
absolutely and with unnerving immediacy.

Johan, blinked a few times, licked his lips in thought and furled his
brow, taken aback by the informality of the eleven year old girl
addressing him by his last name. He cleared his throat, "And who
exactly, miss Leina, would be wanting to fight a little girl?". He
raised a brow quizzically and smirked, reckoning the girl had been put
in her place.

Leina again wasted little time, "Not every question requires a
known answer to be addressed. Why did you enter Mrs. Abnigale's
cottage last night, does your wife know?"

Mr. Lemeus's eyes bulged and he stammered for a response. He cleared
his throat again, this time emitting a much higher tone, and stared
mortified at the girl, who now seemed much too tall and menacing
for an eleven year old. He allowed his jaw to unclench and exhaled with a
frusterated growl. "Who would want to fight a little girl, indeed", he thought.

"Tomorrow. After supper.", Leina confirmed and immediately turned face
to depart, leaving no room for retort or negotiation.

Mr. Lemeus stared thunderstruck at the girl as she walked away, trying
to grasp what exactly had just transpired. He shook his head, his mouth agape and
turned to address his neighbor across the way. With as much discipline
as he could muster, Johan replaced his flustered expression with an
exagerated smile and dramatically issued a friendly wave, "Lovely little girl
you're raising, Haesius!", Lemeus complimented.

Haesius Moore, Leina's uncle on her mother's side, needn't
detect the sarcasm in Johan's voice to discern the truth of the
matter. Haesius winced painfully, offering an apologetic smile
and uncomfortable wave in return.

Madaleina Greystone, the Prodigy of Blackmoor, spent the rest of her
afternoon seated with great posture over two candle-lit books in
her Uncle's study, door locked, quite against her Uncle's
permission. Rather than works of fiction, which her brother adored
being read, this book was a treatise on military tactics by the great
General Hadlam Throeau, and next to it a dictionary containing translations
in three different languages. With delicate, thoughtful penning, she underlined: 

    "By the coin, death becomes of the first stun."

Things usually went on this way where Madeleina was concerned. It's
not that she was rebellious, persay, or blatantly disrespectful, so
much as she was unapologetically direct, uncompromising, and with a
low tolerance for inconvenience. When Leina thought of people, she
thought effort, and the reward was seldom anything but inconvenience
and liability.

Leina had decided, just before her tenth birthday it was best to keep
interactions with people to a minimum, as brief as possible, and only
with those whom she needed or deemed exemplary. These criteria
excluded children almost entirely, save those she could suade to run
errands on her behalf.

Uncle Haesius was one of the few she permitted herself to suffer.
This was mostly because, from the beginning, she 
decisively declared disregard of his rule and instruction.
Whether driven by apathy, exhaustion, or prior trauma
caused growing up with his sister Nume, Haesius had almost
immediately resigned to accomodating Leina's lifestyle. This autonomy
was the main reason Leina prefered staying with Haesius over her
parents.

Her father, a fisherman, from whom she had inherited
excellent balance, was often away for months at a time and was not the
source of the problem. It was Leina's mother, Nume, an incredibly
gifted blacksmith, a voracious reader, polyglot, patriot of knowledge,
and dogmatic, obsessive compulsive perfectionist, whose unshakeable
resolve and peculiarities Leina could only tolerate in limited
doses. Whilst, in theory, there was no better single person in all of
Westhaven she'd elect to learn from, and for this reason no person she
respected and admired more greatly, her mother's rules, constraints,
total lack of positive reinforcement, and brutal criticisms made
keeping her company nearly unbarable. Rules such as the insistance of
a quil being held in a specific manner, or enrangement when Leina
could not blindly recall the twentieth word on a page, in multiple
languages.

Her mother Nume was so lovingly eager, and emotionally desperate, to
transfer her knowledge to her daughter as soon as she aquired it, that
her any inability to do so seemed to cause her physical anguish. But
having read stacks of books at the behest of her mother, Leina had
become increasingly less interested in the selfish direction of her
mother's teachings and one-side prioritization and felt ready to
spiral deeper into topics in a manner of her own choosing. That being
the case, Leina's main reason for returning home was to mentor her
younger brother, who Madeleina, the eleven year old, thought could use
help finding his path in life.

To the dismay of many more than Haesius, and the infuriorating dispair
of Nume, Madeleina was objectively good at getting her way, which is a
nice way of saying, Leina was adept at manipulating her engagements
with people. She was concise and precise with her discourse, cautious
and only as unrevealing as need be, discrete and controlled in her use
of emotion. Her encounters were elaborately and meticulously planned,
premeditated, and every possible branch seemed calculated toward a
maximally favorable outcome. It's safe to say she wasn't just good,
she was abnormally good. Excellent, by measure of one any age. And
where no favorable outcome existed, she would then make one, often at
the expense of those who impaired her plans.

 * * *

The next day Johan Lemeus, a full grown man, waited awkwardly in front
his cottage door, dressed ridiculously in his padded, quilted military
practice garment and holding a practice sword. While a farmer by
trade, Johan had an established reputation for being one of the best
swordsmen within their city of Blacksmoor, Westhaven, having formerly
served the role of Colonel in the Guard.

"What are you wearing?", Leina asked, eyeing Mr. Lemeus quizically as
she approached his yard.

Mr. Lemeus looked down at himself, having dressed for the girl's
benefit, and raised his glance, clearly frustrated and not appreciating
the girl's mockery.

"What I mean is, we won't be using swords.", Leina clarified.

Mr. Lemeus cocked his head with confusion, "You mean to learn fighting
with your hands, then girl?"

"Well, how often am I to be with a sword?", Leina reasoned calmly, "My
hands, I can always count on. And if some day I should not have them
to rely on, you wouldn't have done your job as my teacher."

Mr. Lemeus paused and examined the girl for several moments, wondering
how he might instruct the girl without injuring her, "You're serious
then?"

Leina nodded.

"Well... Come then, let us see what have you."

It was Leina's turn to look confused, "Aren't you going to teach me
the basics?"

"We'll see what you know and where to start", Mr. Lemeus said, giving
the girl a reassuring nod, "Come on then, little babe".

Leina shrugged and bolted towards the man, quickly closing the few
yards between them, her lithe four foot figure posing little
resistance to the air. Fully aware of her physical limitations and the
futility of her situation, she took aim at the one place she knew
would inflict the most damage. And then she let loose, launching a
flimsy punch right towards the man's crotch.

But he was gone before it connected. With a simple side step Johan had
stayed clear of the attack and Leina, unbalanced from momentum, fell to
her hands and skidded along the dirt.

"Ya scrape your knee?", Lemeus asked at first with genuine concern,
"No crying now, I don't teach cryers. Again.", he commanded.

Primed by the humiliating comment, again and again she tried,
furiously, relentlessly, launching herself at her opponent. Each
attempt was stopped dead in its tracks with a stiff-arm or a disarming
side-step. But she didn't complain.

Mr. Lemeus chuckled, but Leina was not affected. She continued to
press forward, fierce, determined and collected.

Mr. Lemeus's attitude grew a bit more stern as he sensed the girls
commitment. "Watch my hips, the direction of my knees. They show where
I will step". Leina didn't need to be told that, her gaze had already
been fixated between the man's hips at her sensitive
target. Nonetheless, she adjusted her strategy, taking the advice to
heart. This time she dashed directly at Johan's leg
mid-side-step.

Johan lifted his leg at the last moment and hopped backwards, causing
the girl to miss, "And what 'xactly do you plan on doing after you
catch my leg?", Johan instigated. "Think, does it put you in a better
position?"

"I'll decide that out when I have you caught", Leina insisted.

This time she leapt through the air, grabbing for the bottom of the
man's pant leg. And she got it. But no sooner had he been caught,
Mr. Leimus jolted his leg away, ripping the fabric out of Leina's
hand, causing her to tumble, chin first, smacking hard into the packed dirt.

"I don't plan on going easy.", Johan warned, "Fighting don't care
how big you are, and it don't accommodate you like your words do."

The outside world seemed fuzzy and less relevant to her suddenly. All
she could focus on was the throbbing pain in her mouth. She tasted
blood, her blood. She had bitten her tongue and it hurt. Her chin
hurt. Her nose hurt. She was disoriented. She heard Mr. Lemeus's voice
just then, he was provoking her, asking if she was alright. What if
she wasn't alright? Would her plan be to just sit there? She
remembered something important. It didn't matter if she was alright,
that wouldn't actually change anything. The lesson wouldn't magically
stop just because she got hurt. Life wouldn't stop. Life wasn't
stopping.

Before she knew it, he was over her, and his hand was extending
towards her. Panic insued and she bolted to her feet. In defiance of
her shaky legs, she charged Mr. Lemeus. Caught off-guard, off-balance,
and stumbling backwards, Mr. Lemeus's desperately tried to bat the
girl away with his hands. To his shock, she lunged again at him,
grabbing securely onto his thigh and sinking her teeth solidly
into his his pant leg.

Mr. Lemeus screamed and pulled at the girl's hair. After several tugs,
he removed her from his leg, tossing her roughly to the ground. He
looked at his leg, where a splotch of blood from the girl's mouth
would now decorated his pant leg. "Renthyr's crow, girl! What would
possess you to such madness?".

The girl collapsed to her back, gasping for air. "By the coin", she
gasped between breaths, "death becomes the first stun."

Johan boggled at the quote, having heard it repeated entirely too
often during his time in service. It's the last thing he wanted to
hear from a young girl. Aggrevated past his limit, he yanked off his
padded tunic by the colar and whipped it to the ground, storming off
towards his home, growing rhetoric about why girls now adays aren't
content with dolls.

"Right then.", Leina called to Johna, deciding quite by herself, "I'll
see you tomorrow. Same time."

Mr. Lemeus's front door slammed loudly.

 * * *

Mr. Lemeus, was not Leina's only mentor. There was Mr. Smithens the
old librarian, Dr. Yitna the mender and potion peddler, Mrs. Cudner
the teller, Gibbon Jones the architect, and her favourite, Zeid the
showoff. At this point she hadn't met Retik, Deveos Retik, the man who
would change her life.

 * * *

* The Quintet
** Book I: The Forming of Prefects

** Book II: The Three Puppets

** Book III: Return of the Headmaster
   
