
* Prologue
The Academy (Book I) is the story of Leina Grey, a young girl who assembles a
faction of prodigies to shield herself from an unbareable society. In her
attempt create a safehaven in which to retreat, Leina incites the biggest power-struggle
Westhaven has ever seen, and caught at it's center is her Academy.

* The Academy

** Chapter I
"Educate me in fighting", Madeleina demanded of her neighbor Johan Lemeus, 
without so much as an exchange of formality.

"Good mornin' to you too, Miss Leina", Johan chuckled defusingly.
"Now who could you possibly be wanting to pick a fight?", he responded 
playfully, his tone reflective of addressing a young child who had just said something cute.

"Any who would want to fight me, Lemeus", Madeleina retorted
with unnerving immediacy.

Johan, blinked a few times with a confused smile, taken aback by the
informalities of the eleven year old girl addressing him by his last name.
He cleared his throat and played along, "And who persay, miss Leina, 
would be wanting to fight a little girl?". He raised a brow condescendingly
and smirked, delighted in his choice of words to put the girl in her place.

Without delay, her patience having depleted, Leina sharply
exclaimed, "You should appreciate not all questions merrit being asked. Why did you enter Mrs. Abnigale's
cottage last night? Should I ask this of your wife?"

Mr. Lemeus's eyes widened as he broke out into cold sweat, stammering over
words for a response. The girl before him now seemed much too tall and menacing
for an eleven year old. "Who would want to fight a little girl, indeed", he thought.

"Tomorrow. After supper.", Leina confirmed and immediately turned face
to depart, leaving no room for negotiation.

Mr. Lemeus stared thunderstruck at the girl as she walked away, trying
to comprehend what exactly had just transpired. He shook his head side to side,
his mouth agape and turned in resignation to address his neighbor across the way.

With as much discipline as he could muster, Johan replaced his flustered expression with an
exagerated smile and issued a friendly wave to his neighbor, "Lovely little girl
you're raising, Haesius!", Lemeus complimented.

Haesius Moore, Leina's uncle on her mother's side, needn't
detect the sarcasm in Johan's voice to discern his
indignance. Haesius winced painfully, offering an apologetic smile
and uncomfortable wave in return.

Madaleina Greystone, the Prodigy of Blackmoor, spent the rest of her
afternoon seated with great posture over two candle-lit books in
her Uncle's study, door locked, quite against her Uncle's
permission. Rather than works of fiction, which her brother adored
being read, this book was a treatise on military tactics by the great
General Hadlam Throeau, and next to it a dictionary containing translations
in three different languages. With delicate, thoughtful penning, she underlined: 

    "By the coin, death becomes of the first stun."

Things usually went on this way where Madeleina was concerned. It's
not that she was rebellious, persay, or blatantly disrespectful, so
much as she was unapologetically direct, uncompromising, and with a
low tolerance for inconvenience. When Leina thought of people, she
thought effort, and the reward was seldom anything but inconvenience
and liability.

Leina had decided, just before her tenth birthday it was best to keep
interactions with people to a minimum, as brief as possible, and only
with those whom she needed or deemed exemplary. These criteria
excluded children almost entirely, save those she could suade to run
errands on her behalf. One in particular being Melinda Sauveneux, a
helpless but hopelessly loyal girl about Leina's age.

Uncle Haesius was another of the rare few she permitted herself to
suffer. A year prior she had asserted his house would be her new
residence, without so much as a conversation, and promised her
disregard of his instruction and rules. Whether driven by apathy,
exhaustion, or rekindled traumatic memories of his equally resolute
sister Nume, Haesius had been quick to resign to accomodating Leina's
lifestyle. This autonomy was the main reason Leina prefered staying
with Haesius over her parents.

Her father Hausue, a fisherman, from whom she had inherited great
balance, was often away for months at a time and was not the source of
the problem. It was Leina's mother, Nume, an incredibly gifted
blacksmith, a voracious reader, polyglot, patriot of knowledge, and
dogmatic, obsessive compulsive perfectionist, whose unshakeable
resolve and peculiarities Leina could only tolerate in limited
doses. Whilst, in theory, there was no better single person in all of
Westhaven she'd elect to learn from, and for this reason no person she
respected and admired more greatly, her mother's rules, constraints,
total lack of positive reinforcement, and brutal criticisms made
keeping her company nearly unbarable. Rules such as the insistance of
a quil being held in a specific manner, or enrangement when Leina
could not blindly recall the twentieth word on a page, in multiple
languages.

Her mother Nume was so lovingly eager, and emotionally desperate, to
transfer her knowledge to her daughter as soon as she aquired it, that
her any inability to do so seemed to cause her physical anguish. But
having read stacks of books at the behest of her mother, Leina had
become increasingly less interested in the selfish direction of her
mother's teachings and one-side prioritization and felt ready to
spiral deeper into topics in a manner of her own choosing. That being
the case, Leina's main reason for returning home was to mentor her
younger brother, who Madeleina, the eleven year old, thought could use
help finding his path in life.

To the dismay of many more than Haesius, and the infuriorating dispair
of Nume, Madeleina was objectively good at getting her way, which is a
nice way of saying, Leina was adept at manipulating her engagements
with people. She was concise and precise with her discourse, cautious
and only as unrevealing as need be, discrete and controlled in her use
of emotion. Her encounters were elaborately and meticulously planned,
premeditated, and every possible branch seemed calculated toward a
maximally favorable outcome. It's safe to say she wasn't just good,
she was abnormally good. Excellent, by measure of one any age. And
where no favorable outcome existed, she would then make one, often at
the expense of those who impaired her plans.

 * * *

The next day Johan Lemeus, a full grown man, waited awkwardly in front
his cottage door, dressed ridiculously in his padded, quilted military
practice garment and holding a practice sword. While a farmer by
trade, Johan had an established reputation for being one of the best
swordsmen within their city of Blacksmoor, Westhaven, having formerly
served the role of Colonel in the Guard.

"What are you wearing?", Leina asked, eyeing Mr. Lemeus quizically as
she approached his yard.

Mr. Lemeus looked down at himself, having dressed for the girl's
benefit, and raised his glance, clearly frustrated and not appreciating
the girl's mockery.

"What I mean is, we won't be using swords.", Leina clarified.

Mr. Lemeus cocked his head with confusion, "You mean to learn fighting
with your hands, then girl?"

"Well, how often am I to be with a sword?", Leina reasoned calmly, "My
hands, I can always count on. And if some day I should not have them
to rely on, you wouldn't have done your job as my teacher."

Mr. Lemeus paused and examined the girl for several moments, wondering
how he might instruct the girl without injuring her, "You're serious
then?"

Leina nodded.

"Well... Come then, let us see what have you."

It was Leina's turn to look confused, "Aren't you going to teach me
the basics?"

"We'll see what you know and where to start", Mr. Lemeus said, giving
the girl a reassuring nod, "Come on then, little babe".

Leina shrugged and bolted towards the man, quickly closing the few
yards between them, her lithe four foot figure posing little
resistance to the air. Fully aware of her physical limitations and the
futility of her situation, she took aim at the one place she knew
would inflict the most damage. And then she let loose, launching a
flimsy punch right towards the man's crotch.

But he was gone before it connected. With a simple side step Johan had
stayed clear of the attack and Leina, unbalanced from momentum, fell to
her hands and skidded along the dirt.

"Ya scrape your knee?", Lemeus asked at first with genuine concern,
"No crying now, I don't teach cryers. Again.", he commanded.

Primed by the humiliating comment, again and again she tried,
furiously, relentlessly, launching herself at her opponent. Each
attempt was stopped dead in its tracks with a stiff-arm or a disarming
side-step. But she didn't complain.

Mr. Lemeus chuckled, but Leina was not affected. She continued to
press forward, fierce, determined and collected.

Mr. Lemeus's attitude grew a bit more stern as he sensed the girls
commitment. "Watch my hips, the direction of my knees. They show where
I will step". Leina didn't need to be told that, her gaze had already
been fixated between the man's hips at her sensitive
target. Nonetheless, she adjusted her strategy, taking the advice to
heart. This time she dashed directly at Johan's leg
mid-side-step.

Johan lifted his leg at the last moment and hopped backwards, causing
the girl to miss, "And what 'xactly do you plan on doing after you
catch my leg?", Johan instigated. "Think, does it put you in a better
position?"

"I'll decide that out when I have you caught", Leina insisted.

This time she leapt through the air, grabbing for the bottom of the
man's pant leg. And she got it. But no sooner had he been caught,
Mr. Leimus jolted his leg away, ripping the fabric out of Leina's
hand, causing her to tumble, chin first, smacking hard into the packed dirt.

"I don't plan on going easy.", Johan warned, "Fighting don't care
how big you are, and it don't accommodate you like your words do."

The outside world seemed fuzzy and less relevant to her suddenly. All
she could focus on was the throbbing pain in her mouth. She tasted
blood, her blood. She had bitten her tongue and it hurt. Her chin
hurt. Her nose hurt. She was disoriented. She heard Mr. Lemeus's voice
just then, he was provoking her, asking if she was alright. What if
she wasn't alright? Would her plan be to just sit there? She
remembered something important. It didn't matter if she was alright,
that wouldn't actually change anything. The lesson wouldn't magically
stop just because she got hurt. Life wouldn't stop. Life wasn't
stopping.

Before she knew it, he was over her, and his hand was extending
towards her. Panic insued and she bolted to her feet. In defiance of
her shaky legs, she charged Mr. Lemeus. Caught off-guard, off-balance,
and stumbling backwards, Mr. Lemeus's desperately tried to bat the
girl away with his hands. To his shock, she lunged again at him,
grabbing securely onto his thigh and sinking her teeth solidly
into his his pant leg.

Mr. Lemeus screamed and pulled at the girl's hair. After several tugs,
he removed her from his leg, tossing her roughly to the ground. He
looked at his leg, where a splotch of blood from the girl's mouth
would now decorated his pant leg. "Renthyr's crow, girl! What would
possess you to such madness?".

The girl collapsed to her back, gasping for air. "By the coin", she
gasped between breaths, "death becomes the first stun."

Johan boggled at the quote, having heard it repeated entirely too
often during his time in service. It's the last thing he wanted to
hear from a young girl. Aggrevated past his limit, he yanked off his
padded tunic by the colar and whipped it to the ground, storming off
towards his home, growing rhetoric about why girls now adays aren't
content with dolls.

"Right then.", Leina called to Johan, deciding quite by herself, "I'll
see you tomorrow. Same time."

Mr. Lemeus's front door slammed loudly.

 * * *

Leina's neighbor, Mr. Lemeus, and her family weren't her only
mentors. There was also Mr. Smithens, the old librarian who for years
had helped guide her through her studies and books selections each
week. When not making incredibly insightful reading recommendations
tailored perfectly to her interests and style, he loved to pitch Leina
with various techniques for organizing and indexing readable
content. Like, his very own, Smithen-dex, for instance, which he had
spent years crafting! The Smithendex, Madeleina thought, was a lovely
and elegant idea which entailed maintaining an index of the library's
topics, rather just an index for locating the papers and books
themselves. Smithens had fifteen or so topics which he maintained,
ranging anywhere from polyglotism, to medicine, to maths, to the
history of cetain meaningful individuals. Under each topic header,
Smithens would painstakingly identifying and record specific chapters,
page numbers, paragraphs, and even line numbers from book or papers
which addressed only these exact topics. Each of these topical indices
he would call a smithindecy, or smity for short. How Mr. Smithens made
time to read all these books and also keep them organized, Leina never
knew, but she imagined the organization only helped in the long run.

Leina often complained when Smithens assigned her a new smities. As
smart and organized as Mr. Smithens was, he had no concept of the
importance of sequences and would often create smities in the order he
discovered content, not the order the content was best learned.

In response, before assigning Leina new smities, crazy Mr. Smithens
began going back and inking dependency arrows onto his Smithendex to
represent which content dependended on others. But every time a new
relevant book or paper showed up at his library's doorstep, his
Smithendex would become an unusable mess of entangled arrows.

That is, until Leina had improvised a solution, on the spot with no
preparation, to replace his Smithendex parchment and messy inked lines
with snippets of parchment tied together by twine or cheap fishing
line. "See, each topic of your Smithendex can be represented by a
collection of these little snippets.", she had said casually and patient,
"Instead of listing resources unmovably on paper under a header, and then trying
to draw lines to connect them, why not actually connect them?"

At the time, crazy Mr. Smithens had thought Madeleina the one crazy,
but he would quickly learn to not make that mistake again. "On the
snippet, we pen the description and mark the location of each
resource, be it a sentence, page or chapter. Then...", she had paused
to rip a snipet of parchment and show the idea in action, "Then you
could punch a quill through the left and right side of each the
snippet... Like this", she showed, "to make two holes; the left hole
will be for other cards to point to or depend on this one and the
right hole will be this card's way of referencing out to other snipets
-- I mean content -- which this one relies on. That way", she
concluded, "If we discovered a new chapter, we could easily rearrange,
add, or remove dependencies."

Leina finished her explanation with a warm and harmless smile, one
which had greatly bothered Mr. Smithens that night.

Apart from Mr. Smithens, there was also Dr. Yitna the healer and
remedy peddler for whom Leina worked helped part time by locating and
collecting wild herbs and weeds.

And whenever she got paid at the end of the week, she was sure to
visit the teller, Mrs. Cudner, to whom she's inquire all the best
investment opportunities. This week, Mrs. Cudner was purchasing food
in bulk.

Gibbon Jones the architect, and her
favourite, Zeid the showoff. At this point she hadn't met Retik,
Ardovus Retik, the man who would change her life.

** Chapter II

It was raining. It had been for the past three days. The streets were
flooded and full of running townsfolk, drenched workers on their way
home, seeking refuge from the downpour. On-duty workers, scampering to
keep the lanterns lit outside their establishments.

Ardovus Retik waited patiently and still, hunched atop a miserable,
cheap wooden chair, swollen with water, and covered by a sopping wet
cigar burned floral patterened cushion. He remained in much the same
position as he had for the previous two nights, on his exposed
third-story balcony. His dark-slate gray raincoat camouflaged
perfectly with the elements, though did little to prevent the torrents
of rain from soaking him to the bone or lessen his desire to throw a
dagger at this one miserable begar below, who had been asking for
change with the same monotone plea for the last four hours. Were he a
less disciplined and principled man, perhaps he'd have done just
that. He surely wouldn't have missed.

From his shadowy third-floor vantage, he surveyed the street below,
his eyes locked on the enterance to the Thrice Filled Flagon. It
wasn't his balcony, persay. Nor was the room to which it was
attached. It was Decus Stromkipre's, a newly made acquaintance. Three
nights prior, before the rain had begun, Ardovus had been perched on
the rooftop of an adjacent Inn, which offered a quite uninspiring
view. So he had walked the wooden bridge connecting his to the
neighboring inn, took the unlocked stairs down to the third floor,
and knocked on the door of a room he had determined would be ideal for
his observations.

He new exactly how to persuade the man Stromkipre, whose habits he had
surveyed the night before. Expensive whiskey, tattered luggage, and a
cheap hotel. When Ardovus knocked on Decus's door and sadly and
honestly explained his unfortunate prediciment, how the rooftop of the
royalty suite was insufficient for conducting his business, Decus was
happy to offer to switch into his royalty suite. And so it came to be
that Decus, as instructed, paid upfront for four days of his room, and
gratefully accepted a fancy looking royaly suite key from Ardovus.

Except Ardovus had neglected to mention, the royalty suite below the
rooftops of the adjacent Inn was not his to give. That night Decus
walked into a stranger's suite, whose lock had been picked and opened
earlier that evening, grateful drank the complimentary bottle of
poisoned champagne which had been waiting for him, and now layed naked
and very much dead in a stranger's tub, to be discovered by the
hysteric cleaning service as a drowned, drunk intruder.

Ardovus felt he could relate to the Decus. His past three evenings had
been dreadfully miserable. The night was humid and windy, and the rain
as relentless and frigid as the sky was black. Still, as the success
of his operation demanded, he waited patiently, still, his eyes
affixed to the tavern below.

** Chapter ?



* The Quintet
** Book I: The Academy

** Book II: The Three Puppets

** Book III: Return of the Headmaster
   
