
* Prologue
The Academy (Book I) is the story of Leina Grey, a young girl who assembles a
faction of prodigies to shield herself from an unbareable society. In her
attempt create a safehaven in which to retreat, Leina incites the biggest power-struggle
Westhaven has ever seen, and caught at it's center is her Academy.

* The Academy

** Chapter I
"Educate me in fighting", Madeleina demanded of her neighbor Johan Lemeus,
without so much as an exchange of formality.

"Good mornin' to you too, Miss Leina", Johan chuckled resignedly, as
if he had grown accustomed to conversations with the young girl starting in
such a manner.

"Show me to fight", said Madeleina again.

"To fight? Who is it you're wanting to fight today?", he responded
playfully, his tone reflective of addressing a young child who had
just said something cute.

"Any who would wish to fight me, Lemeus", Madeleina retorted with
unnerving immediacy.

Johan, blinked a few times with a confused smile, taken aback by the
informalities of the eleven year old girl addressing him by his last name.
He cleared his throat and played along, "And who persay, miss Leina,
would be wanting to fight a little girl?". He raised a brow condescendingly
and smirked, delighted in his choice of words to put the girl in her place.

Without delay, her patience depleted, Leina sharply exclaimed, "I'd
have thought you'd appreciate better than any than not all questions
merrit answers. Why did you enter Mrs. Abnigale's cottage last night?
Perhaps your wife has an answer? It's a girls prerogative to obtain
the means to stave of rapists and to resist tyrranical governments"

Mr. Lemeus's eyes burst open wide and he lunged forward, desperately
slapping his hand over the girls's mouth in a futile attempt to undo
her dangerous words. He looked around and stammered for a response but
his words seemed instead to seep out his pores like a cold sweat. The
girl before him now seemed much too tall and menacing for an eleven
year old. "Wh..Wh.. Who would want to fight a little girl,
indeed", he stammered, his face plastered with an ingenuine sweet smile.

Leina tore the man's hand from her mouth without
tolerance. "Tomorrow. After supper.", Leina confirmed and immediately
turned face to depart, leaving no room for negotiation.

Mr. Lemeus tugged at his collor, allowing his shirt to breath and
stared aghast at the girl as she walked away, trying to
comprehend what exactly had just transpired. He shook his head side to
side, his mouth agape and turned in resignation to address his
neighbor across the way.

With as much cordiality as he could muster, Johan replaced his
flustered expression with an exagerated smile and issued a friendly
wave to his neighbor, "Lovely little girl you're raising, Haesius!",
Lemeus complimented.

Haesius Moore, Leina's uncle on her mother's side, didn't need to
detect the sarcasm in Johan's voice to discern his indignance. Haesius
winced painfully, offering an apologetic smile and uncomfortable wave
in return.

 * * * *

Madaleina Greystone, the Prodigy of Blackmoor, spent the rest of her
afternoon resigned to her Uncle's study, seated with impecable posture
over two candle-lit books, door locked, quite against her Uncle's
permission. Rather than works of fiction, which her brother adored
being read, this book was a western treatise on military tactics by
the great General Hadlam Throeau. Next to it, a dictionary containing
translations in three different languages. With delicate, thoughtful
penning, she underlined and annotated in common tongue:

    "By way the coin, death becomes of the first stun."

Today was an average day where Madeleina was concerned. It's not that
she was rebellious on principle, persay, or blatantly disrespectful,
so much as she was unapologetically direct, uncompromising, and with a
low tolerance for inconvenience. When Leina thought of people, she
thought effort, and she found the reward of people was seldom anything
but inconvenience and liability.

Leina had decided, just before her tenth birthday it was best to keep
interactions with people to a minimum, as brief as possible, and only
with those whom she needed or deemed exemplary. These criteria
excluded children almost entirely, save her little brother and those
few she could suade to run errands on her behalf. One in particular
being Melinda Sauveneux, a hopelessly loyal girl about Leina's
age. Leina treated and cared for the girl as a sister, genuinely, and
with affection and respect. But still there was no task so low that
Leina was too proud to delegate to dear Melinda. Today, it had been
preparing her quills for her night's studies and making her bed.

Uncle Haesius was another of the rare few she permitted herself to
suffer. Having recognized two years prior, the extent of Haesius's
inability to control children, having none of his own, she had decided
(herself) his house would be her new residence, and without so much as
a conversation moved in. In exchange, she offered only the promise
that she intended to fully disregard his instruction and house
rules. Whether driven by apathy, exhaustion, empathy, or rekindled
traumatic memories of his equally resolute and overboard sister Nume,
Haesius had quickly resigned to accomodating Leina's lifestyle. The
autonomy she was afforded was the main reason Leina prefered staying
with Haesius rather than her parents.

Her father Hausue, a fisherman, from whom she had inherited great
balance and patience, was often away for months at a time. He wasn't
the problem. It was Leina's mother, Nume, an incredibly gifted
blacksmith, a voracious reader, polyglot, patriot of knowledge, and
dogmatic, obsessive compulsive perfectionist, whose unshakeable
resolve and peculiarities Leina was losing the ability to
tolerate. Whilst, in theory, there was no better single person in all
of Westhaven more qualified to teach her -- and she wanted to be
taught -- her mother's unrealistic approaches, total lack of positive
reinforcement, and brutal criticisms made keeping company with her
nearly unbarable. Rules such as the insistance of a quil being held in
a specific manner, or rage when Leina could not blindly recall the
twentieth word on a page, in a given language.

Since she could read, Leina was treated and tested as an adult. Nearly
all her interactions with her mother were serious, stern, and
profoundly educational. And while she was grateful for every lesson,
they took their tole. She remembered a lesson she had been taught
around her fifth birthday.

"Sweety, fetch me the Book of Regional Coins from my shelf", Nume had
said to her daughter.

"Yes mother." Leina responded.

When Leina had returned with the book and presented it to her mother,
Nume scolded, "Why did you fetch me the book?"

Leina looked frightened and confused, "You told me to, mother!"

"And? Many people will tell you to do things. Do you do them all?"

"You're my mother"

"So? Put the book back."

"Yes mother...", Leina said in defeat and motioned to put the book back.

"Stop immediately. Why are you putting it back? Why should you?"

Leina froze, not knowing what to do.

"What do you stand to gain?"

Leina continued to stand motionlessly, searching for an answer.

"You're doing it because I asked you to." Nume said sagely. Leina
nodded in reply and smiled.

"Because I provide you with safety."

Leina's smile diminished as she began to realize the depth of the
question she was asked.

"Because I am bigger than you are and can hurt you. Because I teach
you useful things. Because I feed and cloth you."

"Yes mother", Leina said.

"Why did I request the book?"

"I don't know, mother."

"Unacceptable. Even had you a compelling reason why to fetch the book
for me, you'd have done so without even knowing my intent? What if I
was going to hit you with it? Or sell you off to some farmer? Well?
What is my intent?"

"I don't know, mother!" Leina almost cried

"You don't need to know for certain in order to form a hypothesis."

"A what?" Leina said, overwhelmed and squinting in confusion, wiping a
tear from her eye.

"A hypothesis. A formulated explanation. Don't you want to know about
the etymology? That is, where the word comes from? Hypo - thesis. Two
parts. Hypo meaning Underneath and thesis, to place something. You
might place one thing beneath something else to prevent it from
falling. In the same way, you might attempt to support a theory on top
your explanation."

"Oh" said Leina, feeling satisfied with her mother's logic but having entirely
lost the train of thought of the conversation.

"What's your hypothesis?" Nume said impatiently

Leina looked panicked and confused and nearly asked, "my explanation
to support what?" but fearing her mother's fury at her lack of
attention, she closed her eyes harshly and tried to recall the context
of the conversation in her mind.

"My hypothesis of why you want the book is you have a coin and you
don't know how much it's worth? You want to look it up"

"If that's true, what does it mean?"

"Sorry?"

"If your hypothesis is true, what then can you infer"

"Infer? What's the etymology" Leina asked intuitively and
inquisitively.

"To bring into being. To deduce, to lead to a logical conclsion. What
things can you conclude, if you're right that I wish to lookup the
value of a coin?"

"Well, that you have a coin! Or maybe you want to study and prepare
for a meeting with a foreign customer who uses different coins?"

"And how given this information, what might you stand to gain by
helping me in this task?"

"You can teach me about coins! Or give me a coin? Or teach me
about making deals? Or once you earn money you can spend it on
me?"

"Every time I request something of you, you will first ask a question
of my intent. Mother or not, every person should justify their
actions. Otherwise, how can you determine if a person's actions are just?"

Leina nodded, almost on instinct rather than understanding and
excitedly said, "So which is it? Do you have a coin? Can I see? What
do I stand to gain?"

"A lesson" said Nume, "just because you stand to gain from a deal
doesn't mean you will. Now fetch me my tea"

"Yes mother." Leina said dissapointedly

"Echem" Nume said, clearing her throat and staying with violent intent at Leina.

Leina lowered her gaze towards her feet nervously.

"Will you then get tea for anyone who asks for it? What if I were to
pour hot tea on you?..."

Nume was so eager and emotionally desperate to transfer her knowledge
to her daughter as soon as she aquired it, that her any inability to
do so seemed to cause her physical anguish. Having read stacks of
books at the behest of her mother, Leina had become increasingly less
interested in the selfish direction of her mother's teachings and
one-side prioritization and felt compelled to spiral deeper into
topics in a manner of her own choosing. Therefore, Leina had decided
to move in with her uncle, returning home only to mentor her younger
brother, who Madeleina, the eleven year old, thought could use help
finding his path in life.

To the dismay of many more than Haesius, and the satisfaction of Nume,
Madeleina was objectively good at getting her way, which is a nice way
of saying, Leina was adept at manipulating her engagements with
people. She had becomeconcise and precise with her discourse, cautious and
only as unrevealing as need be, discrete and controlled in her use of
emotion. Her encounters were elaborately and meticulously planned,
premeditated, and every possible branch seemed calculated toward a
maximally favorable outcome. It's safe to say she wasn't just good,
she was exceptional. Excellent, by measure of one any age. And
where no favorable outcome existed, she would then make one, often at
the expense of those who impaired her plans.

 * * *

The next day Johan Lemeus, a full grown man, waited awkwardly in front
his cottage door, dressed ridiculously in his padded tunic and holding
a practice sword. While a farmer by trade, Johan had an established
reputation for being one of the best swordsmen within their city of
Blacksmoor, Westhaven, having formerly served as Colonel in
the Guard.

"What are you wearing?", Leina asked, eyeing Mr. Lemeus quizically as
she approached his yard.

Mr. Lemeus examined himself and then stared with frustration at the
girl, having dressed for her benefit.

"What I mean is, we won't be using swords.", Leina clarified.

Mr. Lemeus cocked his head with confusion, "You mean to learn fighting
with your hands, then girl?"

"Well, how often am I to be with a sword?", Leina reasoned calmly, "My
hands, I can always count on. And if some day I should be without
them, I'd say you'd have failed your job as my teacher."

Mr. Lemeus paused for a few moments in thought, wondering how he might
proceed without injuring the girl, "You're serious then?"

Leina nodded.

"Alright, Come then. Let us see what have you."

It was Leina's turn to look confused, "Aren't you going to teach me
the basics?"

"We'll see what you know and where to start", Mr. Lemeus said, giving
the girl a reassuring nod, "Come on then, little babe".

Leina shrugged and bolted towards the man, quickly closing the few
yards between them, her lithe four foot figure posing little
resistance to the air. Fully aware of her physical disadvantage and
the futility of her situation, she took aim at the one place she knew
would inflict the most damage. And then she let loose, launching a
flimsy punch right towards the man's crotch.

But he was gone before it connected. With a simple side step Johan had
stayed clear of the attack and Leina, unbalanced from momentum, fell to
her hands and skidded along the dirt.

"Ya scrape your knee?", Lemeus grinned, "No crying now, I don't teach
cryers. Again.", he commanded.

Primed by the humiliating comment, again and again she tried,
furiously, relentlessly, launching herself at her opponent. Each
attempt was stopped dead in its tracks with a stiff-arm or a disarming
side-step. But she didn't complain.

Mr. Lemeus chuckled, but Leina's emotions were not affected. She continued to
press forward, fierce, determined and collected.

Mr. Lemeus's attitude grew a bit more stern as he sensed the girls
commitment. "Watch my hips, the direction of my knees. They show where
I will step". Leina didn't need to be told that, her gaze had already
been fixated between the man's hips at her sensitive
target. Nonetheless, she heeded the advice and adjusted her strategy,
taking the advice to heart. This time, instead of throwing a punch,
she dashed directly at Johan's leg mid-side-step with both arms.

Johan lifted his leg at the last moment and hopped backwards, causing
the girl to miss and fall into the dirt, "And what 'xactly do you plan
on doing after you catch my leg?", Johan instigated, catching his
breath. "Think carefully, does it put you in a better position?"

"I'll figure that out when I have you caught", Leina insisted.

From the ground she launched herself through the air at Leimus,
grabbing for the bottom of the man's pant leg. And she got it. But no
sooner had he been caught, Mr. Leimus jolted his leg away, ripping the
fabric out of Leina's hand, causing her to again tumble, this time
chin first, smacking hard into the packed dirt.

"I don't plan on going easy.", Johan warned, "A fist don't care
when you're ready to give up"

The outside world seemed fuzzy and less relevant to her suddenly. All
she could focus on was the throbbing pain in her mouth. She tasted
blood, her blood. She had bitten her tongue and it hurt. Her chin
hurt. Her nose hurt. She was disoriented. She heard Mr. Lemeus's voice
just then, he was provoking her, asking if she was alright. What if
she wasn't alright? Would her plan be to just sit there? She
remembered something important. It didn't matter if she was alright,
that wouldn't actually change anything. The lesson wouldn't magically
stop just because she got hurt. Life wouldn't stop. Life wasn't
stopping.

Before she knew it, he was over her, and his hand was extending
towards her. Panic insued. In defiance of her shaky legs, she bolted
to her feet and charged at the off-guard, off-balance Mr. Lemeus.  To
his shock, she lunged again at him, grabbing securely onto his thigh
and sinking her teeth solidly into his his pant leg.

Mr. Lemeus screamed and pulled at the girl's hair. After several tugs,
he removed her from his leg, tossing her roughly to the ground. He
looked at his leg, where a splotch of blood from the girl's mouth
would now decorated his pant leg. "Renthyr's crow, girl! Are you
mad?!".

The girl collapsed to her back, gasping for air. "By the coin", she
gasped between breaths, spitting blood to clear her mouth "death
becomes the first stun."

Johan boggled at the quote, having heard it repeated entirely too
often during his time in service. It's the last thing he wanted to
hear from a young girl. Aggrevated past his limit, he yanked off his
padded tunic by the colar and whipped it to the ground, storming off
towards his home.

"Right then.", Leina called to Johan, deciding quite by herself, "I'll
see you tomorrow. Same time."

Mr. Lemeus's front door slammed loudly.

 * * *

Leina's mother and her neighbor, Mr. Lemeus, weren't her only
mentors. There was also Mr. Smithens, the old librarian who for years
had helped guide her through her studies and books selections each
week. When not making incredibly insightful reading recommendations
tailored perfectly to her interests and style, he loved to pitch Leina
with various techniques for organizing and indexing readable
content. Like, his very own, Smithen-dex, for instance, which he had
spent years crafting! The Smithendex, Madeleina thought, was a lovely
and elegant idea which entailed maintaining an index of the library's
topics, rather just an index for locating the papers and books
themselves. Smithens had fifteen or so topics which he maintained,
ranging anywhere from polyglotism, to medicine, to maths, to the
history of cetain meaningful individuals. Under each topic header,
Smithens would painstakingly identifying and record specific chapters,
page numbers, paragraphs, and even line numbers from book or papers
which addressed only these exact topics. Each of these topical indices
he would call a smithindecy, or smity for short. How Mr. Smithens made
time to read all these books and also keep them organized, Leina never
knew, but she imagined the organization only helped in the long run.

Leina often complained when Smithens assigned her a new smities. As
smart and organized as Mr. Smithens was, he had no concept of the
importance of sequences and would often create smities in the order he
discovered content, not the order the content was best learned.

In response, before assigning Leina new smities, crazy Mr. Smithens
began going back and inking dependency arrows onto his Smithendex to
represent which content dependended on others. But every time a new
relevant book or paper showed up at his library's doorstep, his
Smithendex would become an unusable mess of entangled arrows.

That is, until Leina had improvised a solution, on the spot with no
preparation, to replace his Smithendex parchment and messy inked lines
with snippets of parchment tied together by twine or cheap fishing
line. "See, each topic of your Smithendex can be represented by a
collection of these little snippets.", she had said casually and patient,
"Instead of listing resources unmovably on paper under a header, and then trying
to draw lines to connect them, why not actually connect them?"

At the time, crazy Mr. Smithens had thought Madeleina the one crazy,
but he would quickly learn to not make that mistake again. "On the
snippet, we pen the description and mark the location of each
resource, be it a sentence, page or chapter. Then...", she had paused
to rip a snipet of parchment and show the idea in action, "Then you
could punch a quill through the left and right side of each the
snippet... Like this", she showed, "to make two holes; the left hole
will be for other cards to point to or depend on this one and the
right hole will be this card's way of referencing out to other snipets
-- I mean content -- which this one relies on. That way", she
concluded, "If we discovered a new chapter, we could easily rearrange,
add, or remove dependencies."

Leina finished her explanation with a warm and harmless smile, one
which had greatly bothered Mr. Smithens that night.

Apart from Mr. Smithens, there was also Dr. Yitna the healer and
remedy peddler for whom Leina worked helped part time by locating and
collecting wild herbs and weeds.

And whenever she got paid at the end of the week, she was sure to
visit the teller, Mrs. Cudner, to whom she's inquire all the best
investment opportunities. This week, Mrs. Cudner was purchasing food
in bulk.

Gibbon Jones the architect, and her
favourite, Zeid the showoff. At this point she hadn't met Retik,
Ardovus Retik, the man who would change her life.

** Chapter II

It was raining, frigid rain. It had been for the past three days. The streets were
flooded and full of running townsfolk, drenched workers on their way
home, seeking refuge from the downpour. On-duty workers, scampering to
keep the lanterns lit and signs upright outside their establishments.

Ardovus Retik waited patiently and still, perched miserably on a cheap
rocking chair, its wood swollen with water and covered by a sopping
wet cigar burned floral patterened cushion. He remained in much the
same position as he had for the previous two nights, on his exposed
third-story balcony. His dark-slate gray raincoat camouflaged
perfectly with the elements, though did little to prevent the torrents
of rain from soaking him to the bone or lessen his desire to throw a
dagger at this one miserable begar below, who had been asking for
change with the same monotone plea for the last four hours. Were he a
less disciplined and principled man, perhaps he'd have done just
that. He surely wouldn't have missed.

From his shadowy third-floor vantage, he surveyed the street below,
his eyes locked on the enterance to the Thrice Filled Flagon. It
wasn't his balcony, persay. Nor was the room to which it was
attached. It was Decus Stromkipre's, a newly made acquaintance. Three
nights prior, before the rain had begun, Ardovus had been perched on
the rooftop of an adjacent Inn, which offered a quite uninspiring
view. So he had walked the wooden bridge connecting his to the
neighboring inn, took the unlocked stairs down to the third floor,
and knocked on the door of a room he had determined would be ideal for
his observations.

He new exactly how to persuade the man Stromkipre, whose habits he had
surveyed the night before. Expensive whiskey, tattered luggage, and a
cheap hotel. When Ardovus knocked on Decus's door and sadly and
honestly explained his unfortunate prediciment, how the rooftop of the
royalty suite was insufficient for conducting his business, Decus was
happy to offer to switch into his royalty suite. And so it came to be
that Decus, as instructed, paid upfront for four days of his room, and
gratefully accepted a fancy looking royaly suite key from Ardovus.

Except Ardovus had neglected to mention, the royalty suite below the
rooftops of the adjacent Inn was not his to give. That night Decus
walked into a stranger's suite, whose lock had been picked and opened
earlier that evening, grateful drank the complimentary bottle of
poisoned champagne which had been waiting for him, and now layed naked
and very much dead in a stranger's tub, to be discovered by the
hysteric cleaning service as a drowned, drunk intruder.

Ardovus felt he could relate to the Decus. His past three evenings had
been dreadfully miserable. The night was humid and windy, and the rain
as relentless and frigid as the sky was black. Still, as the success
of his operation demanded, he waited patiently, still, his eyes
affixed to the tavern below.

** Chapter ?



* The Quintet
** Book I: The Academy

** Book II: The Three Puppets

** Book III: Return of the Headmaster
