* What's the world like?
** Religion
Renthyr

** Earth-like, there are several types of areas:
(imagine other planets)
- Rain
- Tundra - Ice-city, snow
- Caves, Mines
- Snow
- Fire
** Technology:
Less, but more (alternate tech).
They have the invention of electricity
** Town
It's a fisher's town, it's raining. It has been for weeks. It has been
for months, without stop.
* What are the characters like?
** Galatea
- Her mother, Nume, is the best blacksmith in town, but kept perpetually poor
- Diteni would have his weapon forged by Nume
- her father, Hausue, was a fisherman
- she has excellent balance
- she is increcibly strong willed and not stopped by fear.
*** Mission -- What does galatea need to do? Why?
- keep boy from dying
* Rest


An assassin finds/rescues Galatea. (Leon the Professional)

Leina is commanding and unafraid. Helps assassin steal, orders
assassin not to kill children, find reasons why they can
help. Founding of the Five Schools. Noone knows where this is. No one
but Galatea has seen the assassin.

Leina demands the Assassin gives her a tattoo to codify their
alliance. Every additional person who joins the school is required to
tattoo a point and connect the dots from an existing point


Races:
- Humans
-- Alchemists

The Collector. The Lords pay tribute to the "Collector".

- The School of Five
Sielaph: Strength, brave (Man)
Cassiel: Charisma, manipulating (Woman)
Ysideos: Wisdom & Intelligence (Woman)
Ditreni: Dexterious (Woman)
Osula: Endurance/Constitution, the outlaster (Man)

The Collector
- Greyskins - humans forced into slavery living underground, injected with serum, passed down through generations.
-- self mutalating, enhancing / experimenting

What threatens everyone? How?

Slavery.

1) An inquisition: Spreading a religion which requires your
service to a Lord.

What is the religion:


The story begins in chaos with an alchemist being torn from his family
to join the Red Shepard's military effort to attack the very same
town. The alchemist is with his wife, his daughter of five, Galatea,
and his youngest son, Reygon, of three. Red Shepard's threatened death
of their families. Military successfully siezes the town. The father
had refused to help, tried to flee / help family escape.  Father and
mother are burned to death as example. Brother was crying, is taken,
Galatea had a better hiding spot.

Q: What is the Red Shepard's cause? Who do they serve?

Galatea taken in by foster parents.

Son/brother becomes her nemisis.

Galatea has a childhood friend

Who

Geryon is a loner, she lives by a set of principles
- Avoid people contact unless necessary
- Change appearances weekly
- Do not stay in one place for too long
- wears a necklace
Plans meticulously



Father told a story about a prophecy? Geryon helps a boy who is a powerful alchemist without knowing it

Neighbor's mother takes her in, she's a tactician for the Red Shepards. Is actually the girl's aunt.



Her father was a blacksmith smith

He doesn't help people

Why is he alone?


Young boy asks for her help.




* The Books
Galatea

The School of Five
1. The Founding
2.
3.


* Prologue

** 1. Greyskins

In the land of Blackmoor, there live three types of people, nobility,
commonfolk, and the greyskin.


Greyskins
