Our story takes place in a land not unlike ours, not yet spoiled by industrialization. 
A peaceful stage set in contrast to upcoming turmoil: the rise of a political faction called the Red Shepherds.

* Pallet

- World is earth-like: Beautiful blue skies, lush woods, cobblestone roads has nights and days; comparable weather; trees, water, ocean, tundra, volcanoes
- Magic is a legend; a lost skill and , not ubiquitous
- Pre-technological revolution, re-industrialization (no mainstream electricity)
- Physics applies: conservation of mass and energy
- Religion exists (name ideas: Renthyr?)
- Political confict: Epic is similar to Game of Thrones in that there are warring cities trying to gain an upper hand

* Home Town
Blackmoor - a wooded neighborhood with dirt roads, several miles from the city proper of Westhaven
Westhaven is a fishing town, it's raining. It has been for weeks. It has been for months, without stop.

## The Oracle
The Oracle is a black large obsidian relic/rune of power that extends into the depths of the earth. It has a special link to the earth, life, and death. In the same way that gravityAll living energy is born from the Oracle and returned upon death. Its mechanics are not fully understood.

## The Soul Seeker's Manual(s)
